### PR TITLE
Manual draining

### PR DESCRIPTION
**Pull request by orenmazor**
hey guys,

I'm trying to manually flush the logs to logzio when my background workers finish their lifecycle (which is so fast that even setting the timeout to 1s is too slow). I played around with setting it to 0, which, in retrospect, was a bad call (it redlined the cpu on all of my boxes because the flushing was nonstop).

This isn't code that's live. just getting feedback at the moment.

/cc @perobertson @hangtwenty

### CODE REVIEW

**Comment by roiravhon** [comment]
Thanks, @orenmazor, that's a great addition!
Just my OCD talking, but can you please change `_flush_the_queue` to `_flush_queue`?

Also, this exposes a thread safety issue, as we can have two flushes running in parallel.
We need to acquire a lock at the beginning of `_flush_queue`, and release it in a `finally` section.

Then, expose a new method (just below the append) that will be called `flush()` that will check if the lock is acquired. if so, it can just return, as the drain is always consuming the entire queue. and if not, just call `_flush_queue()`.

That way we will not force users to call a private method, and keep it thread safe - just two ways to interact with the sender. either append or flush.

Sounds right?

**Comment by orenmazor** [comment]
You’re totally right. I rushed this because I needed this urgently. This is now in production for us and running happily so I’ll circle back and do it cleanly

**Comment by roiravhon** [comment]
Great :) Waiting for a fix.
I would not recommend this for production usage, you might lose some logs in the process

**Comment by orenmazor** [comment]
chewing on adding a lock here. in essence it makes sense to make a flushing lock, but I think the Queue class is already smart enough.

the worst thing thats gonna happen if you try to flush while a flush is happening, is that you'll submit two bulk requests to logzio. e.g the queue will get drained quicker, since you'll have two loops on `_get_messages_up_to_max_allowed_size`, no?

**Comment by roiravhon** [comment]
Basically, you are correct - Queue is thread is safe.
It just seems not deterministic and might prevent future synchronous features (log relations for example)

**Comment by orenmazor** [comment]
fair enough. I'm not privy to the project road map, so to me that seemed like premature optimization for a problem we don't have yet.

but i totally get your point. I'll add a lock.

**Comment by hangtwenty** [comment]
@roiravhon 

It doesn't seem like the lock is necessary to merge this incremental improvement PR, which merely refactors a bit of existing code ... so that a user could use the new method at their own risk. It seems like this PR should be merged and it would be up to the maintainers to do the evolution you're talking about.

If this was a purely open source project maybe it'd be different but Logz is a paid SaaS solution and this is squarely about resolving a pain point that, frankly, is on the list of reasons for us to move away from Logz

**Comment by roiravhon** [comment]
@hangtwenty I agree with your point.
Merged, and version 2.0.6 is live in pypi.

Thanks @orenmazor for this change!

**Comment by orenmazor** [comment]
awesome, thanks guys!

**Comment by hangtwenty** [comment]
Yes thank you!

**Pull request merged**
