### PR TITLE
Handle 201 for successful posts

### PR DESCRIPTION
**Pull request by nloadholtes**

### CODE REVIEW

**Comment by roiravhon** [comment]
Hey @nloadholtes!

Ever experience any issue with this?
Our log receivers should not return 201 as far as I know...

@asafm am i right?

**Comment by nloadholtes** [comment]
I was testing a couple of different configurations, I might have had this lib talking to a regular Elasticsearch cluster. That could be where the 201 came from. If that's not valid for your systems I'm ok with closing this PR

**Comment by asafm** [comment]
@roiravhon @nloadholtes We don't return 201 from our Log Listeners (Receivers)

**Comment by roiravhon** [comment]
So @nloadholtes with your permission, I'm closing this.
Thanks!

**Pull request closed without merging**
